export class elementlocators{

    //element locators
    elementURL = "https://demoqa.com/elements"
    elementbtn = "//span/div/div[text()='Elements']"
    actualelementtitle = "//div/div/div[text()='Elements']"
    expectedelementtitle = "Elements"
    actualelementheader = "//div[text()='Please select an item from left to start practice.']"
    expectedelementheader = "Please select an item from left to start practice."
    
    //textbox locators
    actualtextbox = "//span[text()='Text Box']"
    expectedtextbox = "Text Box"
    textboxfullname = "//input[@placeholder='Full Name']"
    fullname = "Sri Nischal"
    textboxemail = "//input[@placeholder='name@example.com']"
    email = "sri@gmail.com"
    textboxaddress = "//textarea[@placeholder='Current Address']"
    address = "Hyderabad, Telangana"
    textboxpermanentaddress = "//label[text()='Permanent Address']/following::textarea"
    submitbtn = "//button[@class='btn btn-primary']"
    actualname = "//p[text()='Name:']"
    actualemail = "//p[text()='Email:']"
    actualcurrentaddress = "//p[text()='Current Address :']"
    actualpermanentaddress = "//p[text()='Permananet Address :']"

    //checkbox locators
    checkboxbtn = "//span[text()='Check Box']"
    expectedcheckbox = "Check Box"
    checkboxtitle = "//div[text()='Check Box']"
    checkboxexpandallbtn = "//button[@aria-label='Expand all']"
    checkboxcollapseallbtn = "//button[@aria-label='Collapse all']"
    mainfoldercheckbox = "//span[@class='rct-checkbox']"
    mainfoldercheckboxmessage = "//div[@id='result']"
    expectedmainfoldercheckboxmessage = "You have selected :home desktop notes commands documents workspace react angular veu office public private classified general downloads wordFile excelFile"

    //radiobutton locators
    radiobuttonbtn = "//span[text()='Radio Button']"
    expectedradiobuttonmessage = "Radio Button"
    radiobuttontitle = "//div[text()='Radio Button']"
    radiobuttonheading = "//div[text()='Do you like the site?']"
    expectedradiobuttonheading = "Do you like the site?"
    yesradiobtn = "//label[text()='Yes']"
    impressiveradiobtn = "//label[text()='Impressive']"
    radibtnmessage = "//p[@class='mt-3']"
    expectedyesradiobtnmessage = "You have selected Yes"
    expectedimpressiveradiobtnmessage = "You have selected Impressive"

    //buttons locators
    buttonsbtn = "//span[text()='Buttons']"
    expectedbuttonmessage = "Buttons"
    buttonstitle = "//div[text()='Buttons']"
    doubleclickbutton = "//button[text()='Double Click Me']"
    rightclickbutton = "//button[text()='Right Click Me']"
    clickmebutton = "//button[text()='Click Me']"
    actualdoubleclickbtnmessage = "//p[text()='You have done a double click']"
    expecteddoubleclickbtnmessage = "You have done a double click"
    actualrightclickbuttonmessage = "//p[text()='You have done a right click']"
    expectedrightclickbuttonmessage = "You have done a right click"
    actualclickmebuttonmessage = "//p[text()='You have done a dynamic click']"
    expectedclickmebuttonmessage = "You have done a dynamic click"

    // links locators
    linkbtn = "//span[text()='Links']"
    expctedlinkmessage = "Links"
    linktitle = "//div[text()='Links']"
    actualfirstheader = "//strong[text()='Following links will open new tab']"
    expectedfirstheader = "Following links will open new tab"
    actualsecondheader = "//strong[text()='Following links will send an api call']"
    expectedsecondheader = "Following links will send an api call"
    simplelink = "//a[@id='simpleLink']"
    dynamiclink = "//a[@id='dynamicLink']"
    url = "https://demoqa.com/"
    createdapicall = "//a[contains(text(),'Created')]"
    actualapicallmessage = "//p[@id='linkResponse']"
    expectedcreatedapicallmessage = "Link has responded with staus 201 and status text Created"
    nocontentapicall = "//a[contains(text(),'No Content')]"
    expectednocontentapicallmessage = "Link has responded with staus 204 and status text No Content"

    //Broken links and images locators
    brokenlinksbtn = "//span[text()='Broken Links - Images']"
    brokenlinkstitle = "//div[text()='Broken Links - Images']"
    expecetdbrokenlinkmessage = "Broken Links - Images"
    validimagetext = "//p[text()='Valid image']"
    expecetdvalidimagetext = "Valid image"
    validimage = "//div[contains(@class,'col-12 mt-4')]//img[1]"
    actualvalidimagepath = {path: "validimage.png"}
    expectedvalidimagepath = '/element.spec.ts-snapshots/validimage.png'
    brokenimagetext = "//p[text()='Broken image']"
    expectedbrokenimagetext = "Broken image"
    brokenimage = "//img[@src='/images/Toolsqa_1.jpg']"
    actualbrokenimagepath = {path: "brokenimage.png"}
    expectedbrokenimagepath = '/sandbox_carousel.spec.ts-snapshots/brokenimage.png'
    validlinktext = "//p[text()='Valid Link']"
    expecetdvalidlinktext = "Valid Link"
    validlink = "//a[contains(text(),'Click Here for Valid Link')]"
    brokenlinktext = "//p[text()='Broken Link']"
    expectedbrokenlinktext = "Broken Link"
    brokenlink = "//a[contains(text(),'Click Here for Broken Link')]"
    expectedurl = "http://the-internet.herokuapp.com/status_codes/500"
    actualurl = "https://demoqa.com/"

    //upload and download locators
    uploaddownloadbtn = "//span[text()='Upload and Download']"
    expecteduploaddownloadbtn = "Upload and Download"
    uploaddownloadtitle = "//div[text()='Upload and Download']"
    downloadbtn = "//a[text() = 'Download']"
    selectfiletext = "//label[text()='Select a file']"
    expectedselectfiletext = "Select a file"
    choosefilebtn = "//input[@id='uploadFile']"
    expecetdfilename = "Free_Test_Data_500KB_DOCX.docx"
    selectinputfile = 'input[type="file"]'
    selectfile =  './tests/fixtures/Free_Test_Data_500KB_DOCX.docx'
    filepath = "//p[text()='C:\fakepath\Free_Test_Data_500KB_DOCX.docx']"
    expectedfilepath = "C:\fakepath\Free_Test_Data_500KB_DOCX.docx"

    //dynamic properties locators
    dynamicpropertiesbtn = "//span[text()='Dynamic Properties']"
    expecteddynamicmessage = "Dynamic Properties"
    dynamicpropertiestitle = "//div[text()='Dynamic Properties']"
    colorchannge = "//button[text()='Color Change']"
    color = "rgb(220, 53, 69)"
    enableeafter = "//button[text()='Will enable 5 seconds']"
    visibleafter = "//button[text()='Visible After 5 Seconds']"
    expectedvisibleafter = "Visible After 5 Seconds"

    //Web tables locators
    webtablesbtn = "//span[text()='Web Tables']"
    expectedwebtablestext = "Web Tables"
    webtablestitle = "//div[text()='Web Tables']"
    add = "//button[text()='Add']"
    tablevalues = "//div[@class='rt-table']/div[@class='rt-tbody']/div[@class='rt-tr-group']/div[@class='rt-tr -odd']"
    firstname = "//input[@id='firstName']"
    lastname = "//input[@id='lastName']"
    registeremail = "//input[@id='userEmail']"
    age = "//input[@id='age']"
    salary = "//input[@id='salary']"
    department = "//input[@id='department']"
    submit = "//button[@id='submit']"
    addeduser = "(//div[@class='rt-tr -even'])[2]"
    edituser = "//span[@id='edit-record-4']"
    addedfirstname = "(//div[@class='rt-td'])[22]"
    addedlastname = "(//div[@class='rt-td'])[23]"
    addedemail = "(//div[@class='rt-td'])[25]"
    addedage = "(//div[@class='rt-td'])[24]"
    addedsalary = "(//div[@class='rt-td'])[26]"
    addeddepartment = "(//div[@class='rt-td'])[27]"
    deleteuser = "//span[@id='delete-record-4']"
    expectedfirstname = "Sri"
    expectedlastname = "Nischal"
    expectedemail = "sri@example.com"
    actualage = "25"
    expectedage = "26"
    expectedsalary = "20000"
    expecteddepartment = "IT"
    addeduserbeforeediting = "SriNischal25sri@example.com20000IT "
    addeduserafterediting = "SriNischal26sri@example.com20000IT "
    searchbox = "//input[@id='searchBox']"
    searchicon = "//span[@id='basic-addon2']"
    
}