export class widgetlocators{

    //widget locators
    widgets = "//span/div/div[text()='Widgets']"
    widgetsheader = "//div/div/div[text()='Widgets']"
    expectedwidgetstitle = "Widgets"
    actualwidgetheader = "//div[text()='Please select an item from left to start practice.']"
    expectedwidgetheader = "Please select an item from left to start practice."

    //Accordian locators
    accordians = "//span[text()='Accordian']"
    accourdiantext = "//div[text()='Accordian']"
    expectedaccordiantext = "Accordian"
    firstheading = "//div[@id='section1Heading']"
    expectedfirstheading = "What is Lorem Ipsum?"
    secondheading = "//div[@id='section2Heading']"
    expectedsecondheading = "Where does it come from?"
    thirdheading = "//div[@id='section3Heading']"
    expecetedthirdheading = "Why do we use it?"
    firstheadingcontent = "//div[@id='section1Content']"
    secondheadingcontent = "//div[@id='section2Content']"
    thirdheadingcontent = "//div[@id='section3Content']"

    //Auto complete locators
    autocomplete = "//span[text()='Auto Complete']"
    autocompleteheader = "//div[text()='Auto Complete']"
    expectedautocompleteheader = "Auto Complete"
    autocompletefirstheading = "//span[text()='Type multiple color names']"
    expectedautocompletefirstheading = "Type multiple color names"
    autocompletesecondheading = "//span[text()='Type single color name']"
    expectedautocompletesecondheading = "Type single color name"
    multiplecolors = "//input[@id='autoCompleteMultipleInput']"
    singlecolor = "//div[@class='auto-complete__value-container css-1hwfws3']"

    //datepicker locators
    datepicker = "//span[text()='Date Picker']"
    datepickerheader = "//div[text()='Date Picker']"
    expecteddatepickertext = "Date Picker"
    monthyear = "//input[@id='datePickerMonthYearInput']"
    date = "//div[text()='23']"
    monthdropdown = "//select[@class='react-datepicker__month-select']"
    monthoption = "(//div[@class='react-datepicker__month-option'])[9]"
    yearoption = "(//div[@class='react-datepicker__year-option'])[11]"
    timeoption = "(//li[@class='react-datepicker__time-list-item '])[69]"
    yeardropdown = "//select[@class='react-datepicker__year-select']"
    timeselect = "//ul[@class='react-datepicker__time']"
    monthyeartime = "//input[@id='dateAndTimePickerInput']"
    monthselect = "//span[@class='react-datepicker__month-read-view--selected-month']"
    yearselect  = "//span[@class='react-datepicker__year-read-view--selected-year']"

    //slider locators 
    sliderbtn = "//span[text()='Slider']"
    sliderheader = "//div[text()='Slider']"
    expectedslidertext = "Slider"
    slidernumber = "//div[@class='range-slider__tooltip__label']"
    slider = "//input[@class='range-slider range-slider--primary']"
    slidericon = "//div[@class='range-slider__tooltip range-slider__tooltip--auto range-slider__tooltip--bottom']"
    slidervalue = "//input[@id='sliderValue']"

    //progressbar locators
    progressbtn = "//span[text()='Progress Bar']"
    progressheader = "//div[@class='main-header']"
    progressbartext = "//div[@class='mb-3']"
    expectedprogresstext = "Progress Bar"
    progressbar = "//div[@class='progress-bar bg-info']"
    pauseprogressbar = "//div[@aria-valuenow='50']"
    progressbarsuccess = "//div[@aria-valuenow='100']"
    startbtn = "//button[@id='startStopButton']"
    resetbtn = "//button[@id='resetButton']"

    //tabs locators
    tabsbtn = "//span[text()='Tabs']"
    tabsheader = "//div[text()='Tabs']"
    expectedtabstext = "Tabs"
    tabsfirstheader = "//div[text()='Details about Lorem Ipsum']"
    expectedtabsfirstheader = "Details about Lorem Ipsum"
    origin = "//a[@id='demo-tab-origin']"
    use = "//a[@id='demo-tab-use']"
    more = "//a[@id='demo-tab-more']"

    //tooltips locators
    tooltipbtn = "//span[text()='Tool Tips']"
    tooltipheader = "//div[text()='Tool Tips']"
    expectedtooltiptext = "Tool Tips"
    tooltipfirstheader = "//p[text()='Practice Tool Tips']"
    expectedtooltipheader = "Practice Tool Tips"
    hovermetosee = "//button[@id='toolTipButton']"
    hovertoseemetooltip = "//div[text()='You hovered over the Button']"
    expectedhovertoseeme = "You hovered over the Button"
    hovertoseemesearch = "//input[@placeholder='Hover me to see']"
    hovertoseemesearchtooltip = "//div[text()='You hovered over the text field']"
    expectedhovertoseemetooltip = "You hovered over the text field"
    contrary = "//a[text()='Contrary']"
    contrarytext = "//div[text()='You hovered over the Contrary']"
    expectedcontrarytext = "You hovered over the Contrary"
    datetext = "//a[text()='1.10.32']"
    datetooltip = "//div[text()='You hovered over the 1.10.32']"
    expecteddatetext = "You hovered over the 1.10.32"

    //menu locators
    menubtn = "//span[text()='Menu']"
    menuheader = "//div[text()='Menu']"
    expectedmenu = "Menu"
    mainmenu1 = "//a[text()='Main Item 1']"
    expectedmainmenu1 = "Main Item 1"
    mainmenu2 = "//a[text()='Main Item 2']"
    expectedmainmenu2 = "Main Item 2"
    mainmenu3 = "//a[text()='Main Item 3']"
    expecetdmainmenu3 = "Main Item 3"
    subsublist = "//a[text()='SUB SUB LIST »']"
    expctedsublist = "SUB SUB LIST »"

    //Select menu locators
    selectmenubtn = "//span[text()='Select Menu']"
    selectmenuheader = "//div[text()='Select Menu']"
    expectedselectmenutext = "Select Menu"
    selectoption = "(//div[@class=' css-1hwfws3'])[1]"
    selecttitle = "(//div[@class=' css-1hwfws3'])[2]"
    oldstyleselectmenu = "//select[@id='oldSelectMenu']"
    multiselectdropdown = "(//div[@class=' css-1hwfws3'])[3]"
    standardmultiselect = "//select[@id='cars']"
 }
