export class calendarlocators{
    baseURL = "https://automatenow.io/sandbox-automation-testing-practice-website/"
    URL = "https://automatenow.io/sandbox-automation-testing-practice-website/calendars/"
    calendarbtn = "//a[text()='Calendars']"
    actualcalendarheadervalidation = "//h1[text()='Calendars']"
    expectedalendarheadervalidation = "Calendars"
    textboxclicking = "//input[@id='g1065-selectorenteradate']"
    dateselection = "//a[text()='9']"
    submitbutton = "//article/div/div/form/p/button[text() = 'Submit']"
    actualsubmissionmessagevalidation = "//h4[text()='Your message has been sent']"
    expectedsubmissionmessagevalidation = "Your message has been sent"
    actualdatevalidation = "//div[@class='field-value']"
    expecteddatevalidation = "February 9, 2023"
    expectedpreviousmonthdate = "January 9, 2023"
    expectedprevmonthdate = "March 9, 2022"
    expectednextmonthdate = "April 9, 2024"
    expecteddate = "January 9, 2022"
    expectedenterdatevalidation = "09-02-2023"
    previousmonth = "//a[@class='ui-datepicker-prev ui-corner-all']"
    nextmonth = "//a[@class='ui-datepicker-next ui-corner-all']"
    month = "//span[@class='ui-datepicker-month']"
    year = "//span[@class='ui-datepicker-year']"
    prevmonth = "March"
    nextmonths = "April"
    prevyear = "2022"
    nextyear = "2024"
}