export class formfieldlocators {
    baseURL = "https://automatenow.io/sandbox-automation-testing-practice-website/"
    formfield = "//a[text()='Form Fields']"
    enterName = "//div/div/input[@id='g1103-name']"
    name = "Sri Nischal"
    checkboxDrink = "//input[@value='Coffee']"
    checkboxcolor = "//input[@value='Blue']"
    clicksiblings = "//div[@id='ui-id-3']"
    enterEmail = "//input[@id='email']"
    email = 'sri@gmail.com'
    entermessage = "//textarea[@id='contact-form-comment-message']"
    message = 'Test the form fields'
    clicksubmit = "(//button[text()='Submit'])[1]"
    dropdownvalue = "//span[@tabindex='0']"
    actualtext = "//h1[@itemprop='headline']"
    expectedtext = "Form Fields"
    actualresultmessage = "//h4[@id='contact-form-success-header']"
    exepctedresultmessage = "Your message has been sent"
    actualresultname = "(//div[@class='field-value'])[1]"
    expectedresultname = "Sri Nischal"
    actualresultdrink = "(//div[@class='field-value'])[2]"
    expectedresultdrink = "Coffee"
    actualresultcolor = "(//div[@class='field-value'])[3]"
    expectedresultcolor = "Blue"
    actualresultsiblings = "(//div[@class='field-value'])[4]"
    expectedresultsiblings = "No"
    actualresultemail = "(//div[@class='field-value'])[5]"
    expectedresultemail = "sri@gmail.com"
    actualresulttextmessage = "(//div[@class='field-value'])[6]"
    expectedresulttextmessage = "Test the form fields"
}
